### ISSUE TITLE
Code changes but website not updated

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/scratch-wiki.info#6]
Commits have been made, some of of them are quite old now but the website still hasn't been updated to the latest version.
Would someone please update it.

Perhaps we could automate this kind of task too.

**Comment by Kenny2github** [comment]
![image](https://user-images.githubusercontent.com/28599280/93657814-2f941c80-fa68-11ea-97b0-4f37ab3a54d3.png)
![image](https://user-images.githubusercontent.com/28599280/93657819-3c187500-fa68-11ea-9059-325f8efa497b.png)
The website is at the latest version.
